package pl.edu.agh.student.pathfinding.gui;

import java.awt.Dimension;
import java.awt.image.BufferedImage;

import javax.swing.JPanel;

import org.jdesktop.layout.GroupLayout;

import pl.edu.agh.student.pathfinding.gui.panels.BottomPanel;
import pl.edu.agh.student.pathfinding.gui.panels.ImagePanel;

public class MainFrame extends javax.swing.JFrame {

	private BufferedImage image;
	private ImagePanel mainMapPanel;
	private JPanel leftPanel;
	private BottomPanel bottomPanel;

	public MainFrame() {
		initComponents();
	}

	private void initComponents() {

		mainMapPanel = new ImagePanel();
		leftPanel = new JPanel();
		bottomPanel = new BottomPanel(this);
		
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("MainFrame");
		setPreferredSize(new Dimension(800, 600));

		initLeftPanel();
		buildFrameView();

		getAccessibleContext().setAccessibleName("MainFrame");

		pack();
	}

	// code generated by NetBeans Matisse, do not touch
	private void buildFrameView() {
		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.LEADING).add(
				layout.createSequentialGroup()
						.addContainerGap()
						.add(layout
								.createParallelGroup(GroupLayout.LEADING)
								.add(bottomPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.add(layout.createSequentialGroup()
										.add(mainMapPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(leftPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.LEADING).add(
				layout.createSequentialGroup()
						.addContainerGap()
						.add(layout.createParallelGroup(GroupLayout.LEADING)
								.add(leftPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.add(mainMapPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.add(bottomPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE).addContainerGap()));
	}

	private void initLeftPanel() {
		GroupLayout jPanel2Layout = new GroupLayout(leftPanel);
		leftPanel.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.LEADING).add(0, 190,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.LEADING).add(0, 470,
				Short.MAX_VALUE));
	}


	private void reloadMapImage() {
		mainMapPanel.setImage(image);
		mainMapPanel.repaint();
	}
	
	
	public void displayMap(BufferedImage image) {
		this.image = image;
		reloadMapImage();
	}
	
}
